// Builds docs/CONTENT-TODO.md (unverified facts) and docs/TRANSLATION-TODO.md (machine/stale translations)
// from the content files. Run: pnpm --filter @tve/content todo. A test fails if the docs are out of date.
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const docs = join(root, "../../docs");
const LOCALES = ["fr", "nl", "th"];
const read = (p) => JSON.parse(readFileSync(p, "utf8"));
const dirs = (d) =>
  readdirSync(join(root, d), { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .sort();

export function buildDocs() {
  const content = [
    "# Content TODO",
    "",
    "Facts that could not be verified against an official source. Generated from the `todo` fields in",
    "`packages/content` by `pnpm --filter @tve/content todo` — edit the content files, not this file.",
    "",
  ];
  const translation = [
    "# Translation TODO",
    "",
    'Translated files that need review by a native speaker (`reviewStatus: "machine"`) or are older than',
    "the English source (stale). Generated by `pnpm --filter @tve/content todo`.",
    "",
    "**Before launch:** the `disclaimer`, `privacy` and `terms` pages and the footer disclaimer in",
    "`messages/{fr,nl,th}.json` must be reviewed by a native speaker.",
    "",
    "| File | Status | Translated from | English last verified |",
    "|---|---|---|---|",
  ];
  const countries = read(join(root, "countries.json"));
  if (countries.todo?.length)
    content.push("## countries.json", "", ...countries.todo.map((t) => `- ${t}`), "");
  for (const [kind, metaFile] of [
    ["visas", "facts.json"],
    ["guides", "meta.json"],
    ["pages", "meta.json"],
  ]) {
    for (const slug of dirs(kind)) {
      const base = join(root, kind, slug);
      if (!existsSync(join(base, metaFile))) continue;
      const meta = read(join(base, metaFile));
      if (meta.todo?.length)
        content.push(`## ${kind}/${slug}`, "", ...meta.todo.map((t) => `- ${t}`), "");
      for (const l of LOCALES) {
        const f = join(base, `${l}.json`);
        if (!existsSync(f)) {
          translation.push(
            `| ${kind}/${slug}/${l}.json | **missing** | – | ${meta.lastVerified} |`,
          );
          continue;
        }
        const t = read(f);
        const stale = t.translatedFrom < meta.lastVerified;
        if (t.reviewStatus !== "reviewed" || stale)
          translation.push(
            `| ${kind}/${slug}/${l}.json | ${[t.reviewStatus, stale ? "**stale**" : ""].filter(Boolean).join(", ")} | ${t.translatedFrom} | ${meta.lastVerified} |`,
          );
      }
    }
  }
  for (const l of LOCALES)
    translation.push(`| messages/${l}.json | machine (UI strings) | – | – |`);
  return { content: content.join("\n") + "\n", translation: translation.join("\n") + "\n" };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const d = buildDocs();
  writeFileSync(join(docs, "CONTENT-TODO.md"), d.content);
  writeFileSync(join(docs, "TRANSLATION-TODO.md"), d.translation);
  console.log("wrote docs/CONTENT-TODO.md and docs/TRANSLATION-TODO.md");
}
