import type { Country, VisaFacts } from "@tve/content/schema";

const base = {
  officialSources: [
    { label: { en: "x", fr: "x", nl: "x", th: "x" }, url: "https://www.thaievisa.go.th/" },
  ],
  relatedVisas: [],
  todo: [],
  lastVerified: "2026-09-28",
  heroImage: "x",
  popular: false,
  minAge: null,
  minFundsTHB: null,
  localWorkAllowed: false,
  remoteWorkAllowed: false,
  validityMonths: null,
} satisfies Partial<VisaFacts>;

export const visas: VisaFacts[] = [
  {
    ...base,
    slug: "visa-exemption",
    category: "short-stay",
    purposes: ["holiday"],
    maxStayDays: 60,
    extendable: true,
    extensionDays: 30,
    entries: "n/a",
    feeTHB: 0,
    eligibility: "exempt-countries",
  },
  {
    ...base,
    slug: "tourist-tr",
    category: "short-stay",
    purposes: ["holiday"],
    maxStayDays: 60,
    extendable: true,
    extensionDays: 30,
    entries: "single",
    validityMonths: 3,
    feeTHB: 1000,
    eligibility: "all",
  },
  {
    ...base,
    slug: "dtv",
    category: "long-stay",
    purposes: ["remote-work", "muay-thai", "cooking-course"],
    maxStayDays: 180,
    extendable: true,
    extensionDays: 180,
    entries: "multiple",
    validityMonths: 60,
    feeTHB: 10000,
    minFundsTHB: 500000,
    remoteWorkAllowed: true,
    eligibility: "all",
  },
  {
    ...base,
    slug: "non-ed",
    category: "study-training",
    purposes: ["study", "muay-thai"],
    maxStayDays: 90,
    extendable: true,
    extensionDays: 90,
    entries: "single",
    validityMonths: 3,
    feeTHB: 2000,
    eligibility: "all",
  },
  {
    ...base,
    slug: "non-o-retirement",
    category: "retirement",
    purposes: ["retire"],
    maxStayDays: 90,
    extendable: true,
    extensionDays: 365,
    entries: "single",
    validityMonths: 3,
    feeTHB: 2000,
    minFundsTHB: 800000,
    minAge: 50,
    eligibility: "all",
  },
  {
    ...base,
    slug: "non-b-business",
    category: "work-business",
    purposes: ["business-meeting", "work"],
    maxStayDays: 90,
    extendable: true,
    extensionDays: 365,
    entries: "single",
    validityMonths: 3,
    feeTHB: 2000,
    localWorkAllowed: true,
    eligibility: "all",
  },
  {
    ...base,
    slug: "thailand-privilege",
    category: "long-stay",
    purposes: ["holiday", "retire"],
    maxStayDays: null,
    extendable: false,
    extensionDays: null,
    entries: "multiple",
    validityMonths: 60,
    feeTHB: 650000,
    eligibility: "all",
  },
];

export const countries: Country[] = [
  { code: "GB", status: "exempt", stayDays: 60 },
  { code: "IN", status: "voa", stayDays: 15 },
  { code: "NG", status: "visa-required", stayDays: null },
];
